---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: ../../data_bags
  
verifier:
  name: inspec
  sudo: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[chef-vault-demo-cookbook::default]
    attributes:
