---
driver:
  name: dokken
  chef_version: 12.5.1

transport:
  name: dokken

provisioner:
  name: dokken
  data_bags_path: ../../data_bags

verifier:
  name: inspec
  sudo: false

platforms:
- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
