---
driver:
  name: vagrant

provisioner:
  name: shell

verifier:
  name: inspec
  sudo: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: fresh
    provisioner:
      script: fresh.sh
  - name: autoscale
    provisioner:
      script: autoscale.sh
